### ISSUE TITLE
Kibana join-field not matching name (en) Zurich in Switzerland Cantons vector map 

### ISSUE THREAD

**Issue by dschneiter** [elastic/ems-file-service#121]
Kibana 7.1.1 struggled to render data for canton name `Zurich` on a region map displaying Swiss Cantons, using the `Switzerland Cantons` vector map and `name (en)` as join field.

<img width="1164" alt="Screen Shot 2019-08-17 at 21 16 45" src="https://user-images.githubusercontent.com/1571991/63216403-f4bd0800-c134-11e9-8e3f-166fb9913bbd.png">

**Comment by nickpeihl** [comment]
The reason this join does not work for you is the [vector layer](https://maps.elastic.co/#file/switzerland_cantons) uses "Zürich" as the name rather than "Zurich" (note the diacritic). If we change the spelling, we risk breaking existing visualizations of our users. As such, I'm going to close this. 

I would discourage the use of the `name` fields as join fields. There is not always a single consensus on how place names are spelled. For example, [Vietnam is often spelled in several ways even in just the English language](https://en.wikipedia.org/wiki/Names_of_Vietnam#Other_names). 

If possible I suggest using the ISO 3166-2 code as a join field instead. This fields corresponds well with the `geo.region_iso_code` field from the [Elastic Common Schema](https://www.elastic.co/guide/en/ecs/current/ecs-geo.html). 

[This blog post includes more details on joining region maps.](https://www.elastic.co/blog/new-country-subdivision-vectors-in-the-elastic-maps-service)

**Comment by dschneiter** [comment]
@nickpeihl: Can we then please restrict the selection options to name(de)? Unfortunately the alpha-2 codes also don‘t work. What used to work in 6.x is now totally broken - no way to properly render Switzerland Cantons

**Comment by nickpeihl** [comment]
The vector data has not changed between 6.x and 7.x. The English label has always been Zürich. Please let me know if I'm misunderstanding the issue. 

I can not remove or alter any existing fields without potentially breaking existing users' visualizations.

What I can do is add a new field that includes the two letter codes for the cantons. I've reopened #122 to reflect that.

**Comment by dschneiter** [comment]
@nickpeihl thanks for re-opening #122. That will be really helpful.

With respect to names, I don't recall whether I had the option to select localized fields in v6.*, I thought there was only one "name"-option.

I just checked the iso definition, which can be found here. https://www.iso.org/obp/ui/#iso:code:3166:CH.

WIth respect to name it seems that every canton is named in the language spoken in that particular canton. So the iso-list uses different languages for the cantons.

I'm not sure how to best address the current issues in Kibana related to Switzerland Cantons. I simply think that the options for the join field along with the identifier in the vector layer don't make to much sense.

We give choice to the end user which localization of the canton name to be used for the vector layer. While I correctly select `name (en)` this does not seem to work, as for instance for Zurich, the vector layer is using the German localization and not the English one.

I get your point with respect to backward compatibility, so my question is, how can we get there? I guess then it was also broken in the past? When we cannot fix the localized names to work as expected (and match the keys in the vector layer), then we should consider introducing a mixed language name field, that follows the iso standard (https://www.iso.org/obp/ui/#iso:code:3166:CH).

It could be a good idea to refer to the cantons as:
ISO 3166 Canton Code (#122) &
ISO 3166 Canton Name (#121)

Could that be an approach that is working? What do you think about that?
(But then I still don't know what to think about the localized options, which are not supported by the vector layer)
