### ISSUE TITLE
[Maps] EMS France Departments: City of Lyon not in any vector shape

### ISSUE THREAD

**Issue by Chaferfu** [elastic/ems-file-service#133]
**Kibana version**: 7.3

**Elasticsearch version**: 7.3

**Server OS version**: Windows 10

**Original install method (e.g. download page, yum, from source, etc.)**: download page

**Description of the problem including expected versus actual behavior**:
In the France Departments map of EMS, city Lyon is not part of any vector shape, it should be part of the Rhône department. Lyon was previously labelled as "Metropolis of Lyon" which was deleted in 7.3

**Steps to reproduce**:
 1. Go to https://maps.elastic.co/#file/france_departments
 2. Zoom in on France

**Comment by nickpeihl** [comment]
I did a little more research into this and the best authoritative source I can find is [here](https://www.geoportail.gouv.fr/donnees/limites-administratives) showing the Metropolis of Lyon within the Rhone department boundary. So I believe our map is incorrect. 

The [Auvergne-Rhône-Alpes region](https://www.wikidata.org/wiki/Q18338206) properties for `Contains administrative division` separate Rhone and Metropolis of Lyon into separate entities which have boundaries that do not overlap.

There is another Wikidata item called [departmental district of Rhone](https://www.wikidata.org/wiki/Q18914778) which appears to be the successor of [Rhone](https://www.wikidata.org/wiki/Q46130). Rather than make a potentially controversial (and possibly inaccurate) change in Wikidata, I propose we modify the SPARQL query to swap the Wikidata IDs similar to how we do this with [Taiwan in China provinces](https://github.com/elastic/ems-file-service/blob/master/sources/cn/provinces.hjson#L73). 

[This is the query modified with my suggestion](https://tinyurl.com/y4blcsnz).

**Comment by jsanz** [comment]
Thanks for taking a look @nickpeihl, I've also checked

* Open Data from [Eurogeographics](https://eurogeographics.org/products-and-services/open-data/)
* [GADM](https://gadm.org/download_country_v3.html) data for France

And in both sources, Lyon is part of the greater department so I will implement your suggested fix next week.

**Comment by jsanz** [comment]
@Chaferfu this issue was addressed at #137, we plan to release to production all changes in `feature-layers` over the following weeks, thanks for reporting this!
